// Weapon + perk definitions served from a prebuilt static table.
//
// The full Bungie DestinyInventoryItemDefinition manifest is ~190 MB - far too
// large to download and parse inside a serverless function (it times out / runs
// out of memory, so an in-request build never completes). Instead we ship a
// compact weapons-only table (~1.2 MB) and a perk-name map (~0.45 MB) generated
// offline from the manifest. Every lookup here is an instant in-memory map read
// with zero network calls.
//
// These files are regenerated by scripts/build-weapons-table.mjs, run on a
// schedule by .github/workflows/refresh-weapons.yml (which commits + pushes any
// change, auto-triggering a Vercel deploy). The current source manifest version
// is recorded in lib/bungie/data/manifest-version.txt. To refresh by hand:
//   node scripts/build-weapons-table.mjs

import weaponsRaw from "./data/weapons-table.json";
import perkNamesRaw from "./data/perk-names.json";
import perkIconsRaw from "./data/perk-icons.json";

export interface WeaponDefinition {
  itemHash: number;
  name: string;
  icon: string;
  watermark?: string;
  weaponType: string;
  ammoType: string;
  damageType: string;
  tierName: string;
  tierType: number;
  flavorText: string;
  defaultBucketHash: number;
  collectibleHash?: number;
  stats: Record<string, number>;
  intrinsicPerk: string | null;
}

const WEAPONS: Map<number, WeaponDefinition> = (() => {
  const rec = weaponsRaw as unknown as Record<string, WeaponDefinition>;
  const m = new Map<number, WeaponDefinition>();
  for (const key in rec) m.set(Number(key), rec[key]);
  return m;
})();

const PERK_NAMES = perkNamesRaw as unknown as Record<string, string>;
const PERK_ICONS = perkIconsRaw as unknown as Record<string, string>;

export async function getWeaponDefinitions(
  hashes: number[]
): Promise<Map<number, WeaponDefinition>> {
  const result = new Map<number, WeaponDefinition>();
  for (const hash of hashes) {
    const def = WEAPONS.get(hash);
    if (def) result.set(hash, def);
  }
  return result;
}

export async function getWeaponDefinition(
  itemHash: number
): Promise<WeaponDefinition | null> {
  return WEAPONS.get(itemHash) ?? null;
}

export async function getPerkNames(hashes: number[]): Promise<Map<number, string>> {
  const result = new Map<number, string>();
  for (const hash of hashes) {
    const name = PERK_NAMES[hash.toString()];
    if (name) result.set(hash, name);
  }
  return result;
}

export async function getPerkName(hash: number): Promise<string | null> {
  return PERK_NAMES[hash.toString()] ?? null;
}

export async function getPerkIcons(hashes: number[]): Promise<Map<number, string>> {
  const result = new Map<number, string>();
  for (const hash of hashes) {
    const icon = PERK_ICONS[hash.toString()];
    if (icon) result.set(hash, icon);
  }
  return result;
}

// No-op kept for call-site compatibility - definitions are now static, so there
// is nothing to flush to a cache.
export async function flushDefinitionCache(): Promise<void> {}
