// Weapon + perk definitions served from a prebuilt static table.
//
// The full Bungie DestinyInventoryItemDefinition manifest is ~190 MB - far too
// large to download and parse inside a serverless function (it times out / runs
// out of memory, so an in-request build never completes). Instead we ship a
// compact weapons-only table (~1.2 MB) and a perk-name map (~0.45 MB) generated
// offline from the manifest. Every lookup here is an instant in-memory map read
// with zero network calls.
//
// These files are regenerated by scripts/build-weapons-table.mjs, run on a
// schedule by .github/workflows/refresh-weapons.yml (which commits + pushes any
// change, auto-triggering a Vercel deploy). The current source manifest version
// is recorded in lib/bungie/data/manifest-version.txt. To refresh by hand:
//   node scripts/build-weapons-table.mjs

import weaponsRaw from "./data/weapons-table.json";
import perkNamesRaw from "./data/perk-names.json";
import perkDataRaw from "./data/perk-data.json";
import perkIconsRaw from "./data/perk-icons.json";
import { bucketToSlot, type WeaponSlot } from "@/types/bungie";

interface WeaponDefinition {
  itemHash: number;
  name: string;
  icon: string;
  watermark?: string;
  weaponType: string;
  ammoType: string;
  damageType: string;
  tierName: string;
  tierType: number;
  flavorText: string;
  defaultBucketHash: number;
  collectibleHash?: number;
  stats: Record<string, number>;
  intrinsicPerk: string | null;
}

const WEAPONS: Map<number, WeaponDefinition> = (() => {
  const rec = weaponsRaw as unknown as Record<string, WeaponDefinition>;
  const m = new Map<number, WeaponDefinition>();
  for (const key in rec) m.set(Number(key), rec[key]);
  return m;
})();

const PERK_NAMES = perkNamesRaw as unknown as Record<string, string>;
const PERK_DATA = perkDataRaw as unknown as Record<string, { n: string; d: string; s?: Record<string, number> }>;
const PERK_ICONS = perkIconsRaw as unknown as Record<string, string>;

// ── Weapon grouping ────────────────────────────────────────────────────────
// The same gun is re-issued across expansions/seasons (and as Adept/craftable
// variants), each with a DIFFERENT itemHash. To treat "all your Roses" as one
// weapon we group by normalized name + weapon type. Built once from the static
// table, so no manifest regen is needed.

function normalizeWeaponName(name: string): string {
  // Drop the Adept/Timelost/Harrowed/Pinnacle suffix so those pool with the base.
  return name.replace(/\s*\((adept|timelost|harrowed)\)\s*$/i, "").trim().toLowerCase();
}

function groupKeyFor(def: WeaponDefinition): string {
  return `${normalizeWeaponName(def.name)}|${def.weaponType}`;
}

const HASH_TO_GROUP = new Map<number, string>();
const GROUP_TO_HASHES = new Map<string, number[]>();
for (const [hash, def] of WEAPONS) {
  const key = groupKeyFor(def);
  HASH_TO_GROUP.set(hash, key);
  const list = GROUP_TO_HASHES.get(key) ?? [];
  list.push(hash);
  GROUP_TO_HASHES.set(key, list);
}

/**
 * Every itemHash that represents the same weapon as `itemHash` — re-releases
 * across seasons, craftable vs world-drop, and Adept vs non-Adept. Always
 * includes `itemHash` itself; falls back to `[itemHash]` for weapons missing
 * from the static table.
 */
export function getWeaponGroupHashes(itemHash: number): number[] {
  const key = HASH_TO_GROUP.get(itemHash);
  if (!key) return [itemHash];
  return GROUP_TO_HASHES.get(key) ?? [itemHash];
}

export interface HeroWeaponSample { name: string; icon: string; damageType: string; tierType: number }

function shuffle<T>(arr: T[]): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/**
 * Random weapons (icon, name, damage type, tier) from the static table,
 * grouped by their real slot (kinetic/energy/power - via each weapon's
 * defaultBucketHash, the same mapping the actual roll/intersection logic
 * uses) so the landing page's decorative reel never shows a Heavy weapon in
 * the Kinetic slot or similar. Purely decorative, not tied to any player's
 * inventory. Legendary/Exotic only since those read better as small icons
 * than the plainer common/uncommon art. Guarantees a slice of Exotics in
 * each slot's pool - Exotics are a much smaller pool than Legendaries, so a
 * flat random sample would rarely include any at all.
 */
export function getRandomWeaponSample(countPerSlot: number): Record<WeaponSlot, HeroWeaponSample[]> {
  const bySlot: Record<WeaponSlot, { legendaries: HeroWeaponSample[]; exotics: HeroWeaponSample[] }> = {
    kinetic: { legendaries: [], exotics: [] },
    energy: { legendaries: [], exotics: [] },
    power: { legendaries: [], exotics: [] },
  };
  for (const def of WEAPONS.values()) {
    if (!def.icon) continue;
    const slot = bucketToSlot(def.defaultBucketHash);
    if (!slot) continue;
    const sample: HeroWeaponSample = { name: def.name, icon: def.icon, damageType: def.damageType, tierType: def.tierType };
    if (def.tierType === 6) bySlot[slot].exotics.push(sample);
    else if (def.tierType === 5) bySlot[slot].legendaries.push(sample);
  }

  const result = {} as Record<WeaponSlot, HeroWeaponSample[]>;
  for (const slot of ["kinetic", "energy", "power"] as WeaponSlot[]) {
    const { legendaries, exotics } = bySlot[slot];
    shuffle(legendaries);
    shuffle(exotics);
    const exoticCount = Math.min(exotics.length, Math.max(4, Math.round(countPerSlot * 0.25)));
    const legendaryCount = Math.max(0, countPerSlot - exoticCount);
    result[slot] = shuffle([...exotics.slice(0, exoticCount), ...legendaries.slice(0, legendaryCount)]);
  }
  return result;
}

interface PerkInfo { name: string; description: string; stats?: Record<string, number> }

/** Resolve perk hashes to { name, description }. Unknown/cosmetic hashes are omitted. */
export async function getPerkInfos(hashes: number[]): Promise<Map<number, PerkInfo>> {
  const result = new Map<number, PerkInfo>();
  for (const hash of hashes) {
    const d = PERK_DATA[hash.toString()];
    if (d) result.set(hash, { name: d.n, description: d.d, stats: d.s });
  }
  return result;
}

export async function getWeaponDefinitions(
  hashes: number[]
): Promise<Map<number, WeaponDefinition>> {
  const result = new Map<number, WeaponDefinition>();
  for (const hash of hashes) {
    const def = WEAPONS.get(hash);
    if (def) result.set(hash, def);
  }
  return result;
}

export async function getWeaponDefinition(
  itemHash: number
): Promise<WeaponDefinition | null> {
  return WEAPONS.get(itemHash) ?? null;
}

export async function getPerkNames(hashes: number[]): Promise<Map<number, string>> {
  const result = new Map<number, string>();
  for (const hash of hashes) {
    const name = PERK_NAMES[hash.toString()];
    if (name) result.set(hash, name);
  }
  return result;
}

export async function getPerkIcons(hashes: number[]): Promise<Map<number, string>> {
  const result = new Map<number, string>();
  for (const hash of hashes) {
    const icon = PERK_ICONS[hash.toString()];
    if (icon) result.set(hash, icon);
  }
  return result;
}

// No-op kept for call-site compatibility - definitions are now static, so there
// is nothing to flush to a cache.
export async function flushDefinitionCache(): Promise<void> {}
