-- ============================================================
-- 037 - Seed data: Rerolled badge catalog (Core/Crucible/Trials/Iron Banner/PvE/Status)
-- ============================================================
-- v1 scope confirmed in project design notes. Slugs must match
-- lib/badges/catalog.ts's REROLLED_BADGE_SLUGS. Idempotent (ON CONFLICT DO
-- NOTHING) so re-running this migration is safe.
--
-- criteria.rule is a discriminator dispatched by
-- lib/badges/rerolledEvaluators.ts's generic rule functions, so 48 badges
-- share ~20 rule implementations instead of one evaluator per slug. Four
-- badges (trials_proven, trials_verdict, trials_last_rite,
-- iron_banner_rite_of_iron) use rules with no evaluator yet — see
-- lib/badges/catalog.ts's NOT_YET_IMPLEMENTED_REROLLED_SLUGS.

insert into badges (slug, name, description, category, tier, mode, is_repeatable, is_hidden, sort_order, criteria)
values
  -- ============ CORE ============
  ('core_drawn', 'Drawn', 'Complete your first activity with an active Rerolled loadout.',
    'completion', 'bronze', 'core', false, false, 100,
    '{"rule": "first_valid_run"}'::jsonb),
  ('core_bound', 'Bound', 'Complete a match with zero non-rolled final blows.',
    'compliance', 'bronze', 'core', true, false, 110,
    '{"rule": "zero_illegal_final_blows"}'::jsonb),
  ('core_no_deviation', 'No Deviation', 'Complete a match with zero non-rolled final blows and no off-loadout equipment snapshots.',
    'compliance', 'silver', 'core', true, false, 120,
    '{"rule": "zero_illegal_and_loadout_stable"}'::jsonb),
  ('core_threefold', 'Threefold', 'Record at least one final blow with each rolled weapon in one match.',
    'difficulty', 'silver', 'core', true, false, 130,
    '{"rule": "all_rolled_weapons_used"}'::jsonb),
  ('core_full_accord', 'Full Accord', 'Every fireteam member completes the activity with zero non-rolled final blows.',
    'compliance', 'gold', 'core', true, false, 140,
    '{"rule": "fireteam_all_valid"}'::jsonb),
  ('core_chain', 'Chain', 'Five valid Rerolled matches in a row.',
    'streak', 'silver', 'core', false, false, 150,
    '{"rule": "valid_streak", "length": 5}'::jsonb),
  ('core_unbroken_chain', 'Unbroken Chain', 'Ten valid Rerolled matches in a row.',
    'streak', 'gold', 'core', false, false, 160,
    '{"rule": "valid_streak", "length": 10}'::jsonb),
  ('core_verified', 'Verified', 'Complete a scored run eligible for leaderboard placement.',
    'completion', 'bronze', 'core', true, false, 170,
    '{"rule": "leaderboard_eligible"}'::jsonb),
  ('core_sanctioned', 'Sanctioned', 'Complete a verified run under weekly challenge rules.',
    'completion', 'silver', 'core', true, false, 180,
    '{"rule": "weekly_challenge_verified"}'::jsonb),
  ('core_forfeit', 'Forfeit', 'Match had one or more non-rolled final blows.',
    'compliance', 'bronze', 'core', true, true, 190,
    '{"rule": "invalid_marker"}'::jsonb),

  -- ============ CRUCIBLE ============
  ('crucible_writ', 'Crucible Writ', 'Win a Crucible match with a valid Rerolled loadout.',
    'completion', 'bronze', 'crucible', true, false, 200,
    '{"rule": "win_valid_activity", "activity_family": "crucible"}'::jsonb),
  ('crucible_overmatch', 'Overmatch', '30+ defeats in a valid Rerolled Crucible match.',
    'performance', 'bronze', 'crucible', true, false, 210,
    '{"rule": "defeat_threshold", "activity_family": "crucible", "min_defeats": 30}'::jsonb),
  ('crucible_high_mark', 'High Mark', '40+ defeats in a valid Rerolled Crucible match.',
    'performance', 'silver', 'crucible', true, false, 220,
    '{"rule": "defeat_threshold", "activity_family": "crucible", "min_defeats": 40}'::jsonb),
  ('crucible_redline', 'Redline', '50+ defeats in a valid Rerolled Crucible match.',
    'performance', 'gold', 'crucible', true, false, 230,
    '{"rule": "defeat_threshold", "activity_family": "crucible", "min_defeats": 50}'::jsonb),
  ('crucible_apex', 'Apex', 'Finish first on your team in score with a valid Rerolled loadout.',
    'performance', 'silver', 'crucible', true, false, 240,
    '{"rule": "team_score_lead", "activity_family": "crucible"}'::jsonb),
  ('crucible_held_ground', 'Held Ground', 'Win Control with a valid Rerolled loadout and lead your team in objective score or captures.',
    'performance', 'silver', 'crucible', true, false, 250,
    '{"rule": "objective_lead_win", "activity_mode": "control"}'::jsonb),
  ('crucible_lockout', 'Lockout', 'Win Control by mercy or large score margin with a valid Rerolled loadout.',
    'performance', 'gold', 'crucible', true, false, 260,
    '{"rule": "mercy_win", "activity_mode": "control"}'::jsonb),
  ('crucible_solitary', 'Solitary', 'Finish top three in Rumble with a valid Rerolled loadout.',
    'performance', 'silver', 'crucible', true, false, 270,
    '{"rule": "placement_top_n", "activity_mode": "rumble", "max_placement": 3}'::jsonb),
  ('crucible_last_name', 'Last Name', 'Win Rumble with a valid Rerolled loadout.',
    'completion', 'gold', 'crucible', true, false, 280,
    '{"rule": "win_valid_activity", "activity_mode": "rumble"}'::jsonb),
  ('crucible_column_vii', 'Column VII', 'Earn a Seventh Column-type medal while valid.',
    'performance', 'gold', 'crucible', true, false, 290,
    '{"rule": "medal_earned", "medal_key": "seventh_column"}'::jsonb),
  ('crucible_out_of_medals', 'Out of Medals', 'Earn a We Ran Out of Medals-type streak while valid.',
    'performance', 'gold', 'crucible', true, false, 300,
    '{"rule": "medal_earned", "medal_key": "ran_out_of_medals"}'::jsonb),
  ('crucible_ghost_signal', 'Ghost Signal', 'Earn a Ghost in the Night-type medal while valid.',
    'performance', 'gold', 'crucible', true, false, 310,
    '{"rule": "medal_earned", "medal_key": "ghost_in_the_night"}'::jsonb),
  ('crucible_untouched', 'Untouched', 'Finish a match undefeated while valid.',
    'difficulty', 'gold', 'crucible', true, false, 320,
    '{"rule": "undefeated_win", "activity_family": "crucible"}'::jsonb),

  -- ============ TRIALS ============
  ('trials_passage', 'Passage', 'Win one Trials match with a valid Rerolled loadout.',
    'completion', 'bronze', 'trials', true, false, 400,
    '{"rule": "card_win_count", "min_wins_on_card": 1}'::jsonb),
  ('trials_passage_iii', 'Passage III', 'Win three Trials matches on one card with valid Rerolled loadouts.',
    'completion', 'silver', 'trials', true, false, 410,
    '{"rule": "card_win_count", "min_wins_on_card": 3}'::jsonb),
  ('trials_passage_vii', 'Passage VII', 'Win seven Trials matches on one card with valid Rerolled loadouts.',
    'completion', 'gold', 'trials', true, false, 420,
    '{"rule": "card_win_count", "min_wins_on_card": 7}'::jsonb),
  ('trials_lighthouse_writ', 'Lighthouse Writ', 'Go Flawless while using valid Rerolled loadouts for every tracked match.',
    'difficulty', 'platinum', 'trials', true, false, 430,
    '{"rule": "flawless_card", "activity_family": "trials"}'::jsonb),
  ('trials_proven', 'Proven', 'Win a round-based match while leading your team in final blows with only rolled weapons.',
    'performance', 'gold', 'trials', true, false, 440,
    '{"rule": "round_final_blow_lead"}'::jsonb),
  ('trials_verdict', 'Verdict', 'Win a valid match with no round containing a non-rolled final blow.',
    'compliance', 'gold', 'trials', true, false, 450,
    '{"rule": "no_round_illegal"}'::jsonb),
  ('trials_last_rite', 'Last Rite', 'Win the final round with a rolled-weapon final blow.',
    'performance', 'gold', 'trials', true, false, 460,
    '{"rule": "final_round_rolled_win"}'::jsonb),
  ('trials_cardbound', 'Cardbound', 'Complete an entire Trials card while keeping the Rerolled loadout rule active.',
    'difficulty', 'gold', 'trials', true, false, 470,
    '{"rule": "card_complete_valid", "activity_family": "trials"}'::jsonb),

  -- ============ IRON BANNER ============
  ('iron_banner_ironbound', 'Ironbound', 'Win an Iron Banner match with a valid Rerolled loadout.',
    'completion', 'bronze', 'iron_banner', true, false, 500,
    '{"rule": "win_valid_activity", "activity_family": "iron_banner"}'::jsonb),
  ('iron_banner_standard', 'Standard', 'Finish top two on your team in a valid Iron Banner match.',
    'performance', 'silver', 'iron_banner', true, false, 510,
    '{"rule": "placement_top_n", "activity_family": "iron_banner", "max_placement": 2, "scope": "team"}'::jsonb),
  ('iron_banner_banner_writ', 'Banner Writ', 'Complete five valid Iron Banner matches during one Iron Banner week.',
    'difficulty', 'silver', 'iron_banner', true, false, 520,
    '{"rule": "weekly_match_count", "activity_family": "iron_banner", "min_matches": 5}'::jsonb),
  ('iron_banner_forged', 'Forged', 'Earn a high-score Iron Banner badge while valid.',
    'performance', 'gold', 'iron_banner', true, false, 530,
    '{"rule": "medal_earned", "medal_key": "iron_banner_high_score", "activity_family": "iron_banner"}'::jsonb),
  ('iron_banner_rite_of_iron', 'Rite of Iron', 'Complete an entire Iron Banner session with no invalid Rerolled matches.',
    'difficulty', 'platinum', 'iron_banner', true, false, 540,
    '{"rule": "session_all_valid", "activity_family": "iron_banner"}'::jsonb),

  -- ============ PVE ============
  ('pve_vanguard_writ', 'Vanguard Writ', 'Complete a strike or playlist activity with a valid Rerolled loadout.',
    'completion', 'bronze', 'pve', true, false, 600,
    '{"rule": "complete_valid_activity", "activity_family": "vanguard"}'::jsonb),
  ('pve_ordeal', 'Ordeal', 'Complete a Nightfall with a valid Rerolled loadout.',
    'completion', 'silver', 'pve', true, false, 610,
    '{"rule": "complete_valid_activity", "activity_family": "nightfall"}'::jsonb),
  ('pve_grand_ordeal', 'Grand Ordeal', 'Complete a Grandmaster Nightfall with a valid Rerolled loadout.',
    'completion', 'gold', 'pve', true, false, 620,
    '{"rule": "complete_valid_activity", "activity_family": "gm"}'::jsonb),
  ('pve_fireteam_accord', 'Fireteam Accord', 'Full fireteam completes a PvE activity with valid Rerolled loadouts.',
    'compliance', 'gold', 'pve', true, false, 630,
    '{"rule": "fireteam_all_valid", "activity_family": "pve"}'::jsonb),
  ('pve_encounter_writ', 'Encounter Writ', 'Complete one encounter with a valid Rerolled loadout.',
    'completion', 'bronze', 'pve', true, false, 640,
    '{"rule": "complete_valid_activity", "activity_family": ["dungeon", "raid"], "scope": "encounter"}'::jsonb),
  ('pve_deep_writ', 'Deep Writ', 'Complete a dungeon with a valid Rerolled loadout.',
    'completion', 'silver', 'pve', true, false, 650,
    '{"rule": "complete_valid_activity", "activity_family": "dungeon"}'::jsonb),
  ('pve_raid_writ', 'Raid Writ', 'Complete a raid encounter or full raid with a valid Rerolled loadout.',
    'completion', 'silver', 'pve', true, false, 660,
    '{"rule": "complete_valid_activity", "activity_family": "raid"}'::jsonb),
  ('pve_no_reserve', 'No Reserve', 'Complete a valid activity where all rolled weapons were used for final blows.',
    'difficulty', 'silver', 'pve', true, false, 670,
    '{"rule": "all_rolled_weapons_used", "activity_family": "pve"}'::jsonb),

  -- ============ STATUS / LEGACY (manually granted) ============
  ('status_founder', 'Founder', 'Played during closed beta or early launch window.',
    'founder', 'special', 'status_legacy', false, false, 800,
    '{"rule": "manual_grant"}'::jsonb),
  ('status_developer', 'Developer', 'Project maintainer.',
    'founder', 'special', 'status_legacy', false, false, 810,
    '{"rule": "manual_grant"}'::jsonb),
  ('status_advisor', 'Advisor', 'Helped shape rules, testing, or design.',
    'founder', 'special', 'status_legacy', false, false, 820,
    '{"rule": "manual_grant"}'::jsonb),
  ('status_invict', 'Invict', 'Original Invict group / founding community badge.',
    'founder', 'special', 'status_legacy', false, false, 830,
    '{"rule": "manual_grant"}'::jsonb)
on conflict (slug) do nothing;
